/**
 * Shared harness for the update suites (plan 45-02).
 *
 * Builds a real, temporary app-data tree from the checksum-pinned prior-version
 * fixture generated by `desktop/scripts/create-upgrade-fixture.ps1`
 * (desktop/test-fixtures/prior-version) and drives it with the real
 * `nodeDataFs`, so the suites exercise the exact ps1-emitted manifest and the
 * real filesystem DataFs — not a fake.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createHash } from "node:crypto";
import {
  initializeAppDataPaths,
  nodeDataFs,
  type AppDataPaths,
  type DataFs,
} from "../../src/data/app-data-layout";
import { hashFile } from "../../src/data/backup";

export const DESKTOP_DIR = path.resolve(__dirname, "..", "..");
export const FIXTURE_ROOT = path.join(DESKTOP_DIR, "test-fixtures", "prior-version");
export const FIXTURE_MANIFEST_PATH = path.join(FIXTURE_ROOT, "fixture-manifest.json");
export const FIXTURE_DATA = path.join(FIXTURE_ROOT, "data");
export const FIXTURE_MIGRATION_JSON = path.join(FIXTURE_ROOT, "migration.json");
/** The upgrade target schema version used across the update suites. */
export const TARGET_SCHEMA_VERSION = 2;
/** The version the upgrade suites upgrade TO (must be > the fixture 0.1.0). */
export const UPGRADE_APP_VERSION = "0.2.0";
/** The fixture's committed prior runtime version (schemaVersion 1). */
export const FIXTURE_RUNTIME_VERSION = "0.1.0";

export interface TempAppData {
  fs: DataFs;
  appData: AppDataPaths;
  root: string;
  cleanup: () => Promise<void>;
}

/** Create a fresh temp app-data tree with the fixture's data + version metadata. */
export async function makeFixtureAppData(): Promise<TempAppData> {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "novelmind-upgrade-"));
  const fsReal = nodeDataFs();
  const appData = await initializeAppDataPaths(fsReal, { userDataDir: root });
  seedDataSync(appData.data, FIXTURE_DATA);
  fs.copyFileSync(FIXTURE_MIGRATION_JSON, appData.migrationMeta);
  return {
    fs: fsReal,
    appData,
    root,
    cleanup: async () => {
      for (let attempt = 0; attempt < 5; attempt += 1) {
        try {
          fs.rmSync(root, { recursive: true, force: true });
          return;
        } catch {
          await new Promise((r) => setTimeout(r, 500));
        }
      }
    },
  };
}

/** Hash every file under appData.data, keyed by the app-data-relative path. */
export async function dataHashes(
  fsLike: DataFs,
  appData: AppDataPaths,
): Promise<Record<string, string>> {
  const result: Record<string, string> = {};
  for (const [rel, abs] of listFiles(appData.data)) {
    result[rel] = (await hashFile(fsLike, abs)).hash;
  }
  return result;
}

/** [relative path, absolute path] pairs for every file under a directory tree. */
export function listFiles(root: string): [string, string][] {
  const out: [string, string][] = [];
  const visit = (dir: string): void => {
    for (const entry of fs.readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (fs.statSync(full).isDirectory()) {
        visit(full);
      } else {
        out.push([path.relative(root, full).replace(/\\/g, "/"), full]);
      }
    }
  };
  visit(root);
  return out.sort((a, b) => a[0].localeCompare(b[0]));
}

/** The fixture's own data hashes (keyed by data/-relative path). */
export function fixtureDataHashes(): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [rel, abs] of listFiles(FIXTURE_DATA)) {
    result[rel] = sha256FileSync(abs);
  }
  return result;
}

function sha256FileSync(abs: string): string {
  const hash = createHash("sha256");
  hash.update(fs.readFileSync(abs));
  return hash.digest("hex");
}

/** Recursively copy a directory tree synchronously (content bytes identical). */
function seedDataSync(destRoot: string, srcRoot: string): void {
  for (const entry of fs.readdirSync(srcRoot)) {
    const srcAbs = path.join(srcRoot, entry);
    const destAbs = path.join(destRoot, entry);
    if (fs.statSync(srcAbs).isDirectory()) {
      fs.mkdirSync(destAbs, { recursive: true });
      seedDataSync(destAbs, srcAbs);
    } else {
      fs.copyFileSync(srcAbs, destAbs);
    }
  }
}
