"""add skill_run backfill origin columns

Revision ID: 085fffd58ee9
Revises: 20260802_derivative_asset01
Create Date: 2026-08-05 20:27:20.680064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085fffd58ee9'
down_revision: Union[str, Sequence[str], None] = '20260802_derivative_asset01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_runs', sa.Column('origin', sa.String(length=16), server_default='user_sse', nullable=False))
    op.add_column('skill_runs', sa.Column('backfill_dimension', sa.String(length=40), nullable=True))
    op.add_column('skill_runs', sa.Column('user_message_id', sa.Integer(), nullable=True))
    op.create_index('uq_skill_runs_backfill_inflight', 'skill_runs', ['owner_id', 'novel_id', 'backfill_dimension'], unique=True, postgresql_where=sa.text("origin = 'chat_backfill' AND status IN ('queued', 'running')"))
    op.create_foreign_key('fk_skill_runs_user_message_id', 'skill_runs', 'reader_messages', ['user_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_skill_runs_user_message_id', 'skill_runs', type_='foreignkey')
    op.drop_index('uq_skill_runs_backfill_inflight', table_name='skill_runs', postgresql_where=sa.text("origin = 'chat_backfill' AND status IN ('queued', 'running')"))
    op.drop_column('skill_runs', 'user_message_id')
    op.drop_column('skill_runs', 'backfill_dimension')
    op.drop_column('skill_runs', 'origin')
    # ### end Alembic commands ###
