"""sync chunk hierarchy indexes

Revision ID: 6535bbf6de8f
Revises: 17memqual01
Create Date: 2026-07-19 01:00:50.175786

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6535bbf6de8f'
down_revision: Union[str, Sequence[str], None] = '17memqual01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chunk_hierarchy_nodes_build_id'), 'chunk_hierarchy_nodes', ['build_id'], unique=False)
    op.drop_index(op.f('idx_text_chunks_hierarchy_node'), table_name='text_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_text_chunks_hierarchy_node'), 'text_chunks', ['hierarchy_build_id', 'hierarchy_node_id'], unique=False)
    op.drop_index(op.f('ix_chunk_hierarchy_nodes_build_id'), table_name='chunk_hierarchy_nodes')
    # ### end Alembic commands ###
