"""add_text_chunks_fanfiction_chapters_ai_usage_logs

Revision ID: d8a307bac6c7
Revises: 3c73d82690cf
Create Date: 2026-06-06 15:47:47.094020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a307bac6c7'
down_revision: Union[str, Sequence[str], None] = '3c73d82690cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_model_name'), 'ai_usage_logs', ['model_name'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_novel_id'), 'ai_usage_logs', ['novel_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_task_type'), 'ai_usage_logs', ['task_type'], unique=False)
    op.create_table('text_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_chunks_chapter_id'), 'text_chunks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_text_chunks_novel_id'), 'text_chunks', ['novel_id'], unique=False)
    op.create_table('fanfiction_chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fanfiction_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('style_score', sa.Float(), nullable=True),
    sa.Column('rag_context', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fanfiction_id'], ['fan_fictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fanfiction_chapters_fanfiction_id'), 'fanfiction_chapters', ['fanfiction_id'], unique=False)
    op.add_column('novels', sa.Column('chapter_count', sa.Integer(), nullable=False))
    op.add_column('novels', sa.Column('word_count', sa.Integer(), nullable=False))
    op.add_column('novels', sa.Column('style_fingerprint', sa.JSON(), nullable=True))
    op.alter_column('novels', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('novels', 'total_chapters')
    op.drop_column('novels', 'total_words')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('total_words', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('novels', sa.Column('total_chapters', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('novels', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('novels', 'style_fingerprint')
    op.drop_column('novels', 'word_count')
    op.drop_column('novels', 'chapter_count')
    op.drop_index(op.f('ix_fanfiction_chapters_fanfiction_id'), table_name='fanfiction_chapters')
    op.drop_table('fanfiction_chapters')
    op.drop_index(op.f('ix_text_chunks_novel_id'), table_name='text_chunks')
    op.drop_index(op.f('ix_text_chunks_chapter_id'), table_name='text_chunks')
    op.drop_table('text_chunks')
    op.drop_index(op.f('ix_ai_usage_logs_task_type'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_novel_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_model_name'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    # ### end Alembic commands ###
