"""add_lease_id_to_import_jobs

Revision ID: e2ea8ac6e513
Revises: 9c7f25bb06e8
Create Date: 2026-06-12 23:38:10.188936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2ea8ac6e513'
down_revision: Union[str, Sequence[str], None] = '9c7f25bb06e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('lease_id', sa.String(length=64), nullable=True))
    op.add_column('import_jobs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('import_jobs', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_import_jobs_content_hash'), 'import_jobs', ['content_hash'], unique=False)
    # text_chunks.search_vector: drop GIN index first, then change type
    op.drop_index(op.f('idx_text_chunks_search'), table_name='text_chunks', postgresql_using='gin')
    op.alter_column('text_chunks', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_chunks', 'search_vector',
               existing_type=sa.Text(),
               type_=postgresql.TSVECTOR(),
               existing_nullable=True)
    op.create_index(op.f('idx_text_chunks_search'), 'text_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_import_jobs_content_hash'), table_name='import_jobs')
    op.drop_column('import_jobs', 'content_hash')
    op.drop_column('import_jobs', 'lease_expires_at')
    op.drop_column('import_jobs', 'lease_id')
    # ### end Alembic commands ###
