"""add_reading_progress_to_novels

Revision ID: f3c8b7b2dbf7
Revises: d8a307bac6c7
Create Date: 2026-06-11 13:12:05.798803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c8b7b2dbf7'
down_revision: Union[str, Sequence[str], None] = 'd8a307bac6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('reading_progress', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novels', 'reading_progress')
    # ### end Alembic commands ###
